sonar.organization=nfma
sonar.projectKey=nfma_hexagonal-architecture-validator
sonar.projectName=hexagonal-architecture-validator
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=.github,src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.rs
sonar.exclusions=tests/**,target/**
sonar.rust.cargo.manifestPaths=Cargo.toml
sonar.rust.lcov.reportPaths=lcov.info
